spring:
  application:
    name: project2

  kafka:

    bootstrap-servers: localhost:9092


    streams:
      application-id: uppercase-stream-app
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde


    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
        auto.register.schemas: true
